import type { Recipe } from "./types";

const S = { salt: "salt", oil: "olive oil", garlic: "garlic", butter: "butter", rice: "rice", pasta: "pasta", soy: "soy sauce", flour: "flour", stock: "chicken stock", tomatoes: "canned tomatoes", spices: "dried spices", sugar: "sugar", vinegar: "vinegar", honey: "honey" };

/**
 * Dinner library. Ingredients reference FoodKeeper ids; `key` ingredients make the dish,
 * `optional` ones are nice-to-have. Staples are assumed free and always in stock.
 */
export const RECIPES: Recipe[] = [
  {
    id: "spinach-strawberry-chicken-salad",
    title: "Spinach-strawberry salad with grilled chicken",
    emoji: "🥗",
    minutes: 25,
    servings: 2,
    ingredients: [
      { foodId: "spinach", key: true },
      { foodId: "strawberries", key: true },
      { foodId: "chicken_breast", key: true },
      { foodId: "lemons", optional: true },
      { foodId: "parmesan", optional: true },
    ],
    staples: [S.oil, S.salt, S.honey, S.vinegar],
    steps: ["Season chicken, grill 6 min a side, rest and slice.", "Whisk oil, vinegar, honey, salt.", "Toss spinach and halved strawberries in dressing, top with chicken."],
    popularity: 9,
    source: "library",
  },
  {
    id: "chicken-fajitas",
    title: "Chicken fajitas",
    emoji: "🌯",
    minutes: 30,
    servings: 3,
    ingredients: [
      { foodId: "chicken_breast", key: true },
      { foodId: "bell_pepper", key: true },
      { foodId: "onions" },
      { foodId: "tortillas", key: true },
      { foodId: "cheddar", optional: true },
      { foodId: "limes", optional: true },
      { foodId: "avocados", optional: true },
    ],
    staples: [S.oil, S.spices, S.salt],
    steps: ["Slice chicken, peppers and onion.", "Sear chicken hard in a hot pan, add veg and spices.", "Warm tortillas, pile everything in."],
    popularity: 3,
    source: "library",
  },
  {
    id: "lemon-garlic-salmon",
    title: "Lemon-garlic salmon with rice and spinach",
    emoji: "🐟",
    minutes: 25,
    servings: 2,
    ingredients: [
      { foodId: "salmon", key: true },
      { foodId: "lemons" },
      { foodId: "spinach", optional: true },
    ],
    staples: [S.rice, S.garlic, S.butter, S.salt],
    steps: ["Start rice.", "Pan-sear salmon skin-side down 4 min, flip, add butter, garlic, lemon.", "Wilt spinach in the pan juices."],
    popularity: 6,
    source: "library",
  },
  {
    id: "spinach-cheddar-omelet",
    title: "Spinach and cheddar omelet with toast",
    emoji: "🍳",
    minutes: 15,
    servings: 1,
    ingredients: [
      { foodId: "eggs", key: true },
      { foodId: "spinach", key: true },
      { foodId: "cheddar" },
      { foodId: "milk", optional: true },
      { foodId: "bread", optional: true },
    ],
    staples: [S.butter, S.salt],
    steps: ["Whisk eggs with a splash of milk.", "Wilt spinach in butter, pour eggs over.", "Add cheddar, fold, serve on toast."],
    popularity: 10,
    source: "library",
  },
  {
    id: "beef-tacos",
    title: "Weeknight beef tacos",
    emoji: "🌮",
    minutes: 25,
    servings: 3,
    ingredients: [
      { foodId: "ground_beef", key: true },
      { foodId: "tortillas", key: true },
      { foodId: "tomatoes" },
      { foodId: "cheddar" },
      { foodId: "onions", optional: true },
      { foodId: "avocados", optional: true },
      { foodId: "lettuce", optional: true },
    ],
    staples: [S.spices, S.salt, S.oil],
    steps: ["Brown beef with onion and spices.", "Dice tomato and avocado.", "Warm tortillas, assemble."],
    popularity: 1,
    source: "library",
  },
  {
    id: "avocado-toast-eggs",
    title: "Avocado toast with fried eggs",
    emoji: "🥑",
    minutes: 10,
    servings: 2,
    ingredients: [
      { foodId: "bread", key: true },
      { foodId: "avocados", key: true },
      { foodId: "eggs", key: true },
      { foodId: "tomatoes", optional: true },
      { foodId: "lemons", optional: true },
    ],
    staples: [S.salt, S.oil],
    steps: ["Toast bread.", "Mash avocado with lemon and salt.", "Fry eggs, stack, finish with pepper."],
    popularity: 7,
    source: "library",
  },
  {
    id: "strawberry-banana-smoothie-bowl",
    title: "Strawberry-banana yogurt bowl",
    emoji: "🍓",
    minutes: 5,
    servings: 2,
    ingredients: [
      { foodId: "strawberries", key: true },
      { foodId: "bananas", key: true },
      { foodId: "yogurt", key: true },
      { foodId: "milk", optional: true },
      { foodId: "blueberries", optional: true },
    ],
    staples: [S.honey, "oats"],
    steps: ["Blend banana, half the strawberries, yogurt and a splash of milk.", "Top with sliced strawberries, oats and honey."],
    popularity: 14,
    source: "library",
  },
  {
    id: "chicken-stir-fry",
    title: "Chicken and pepper stir-fry",
    emoji: "🥡",
    minutes: 25,
    servings: 3,
    ingredients: [
      { foodId: "chicken_breast", key: true },
      { foodId: "bell_pepper", key: true },
      { foodId: "broccoli", optional: true },
      { foodId: "ginger", optional: true },
      { foodId: "onions", optional: true },
    ],
    staples: [S.rice, S.soy, S.garlic, S.oil, S.honey],
    steps: ["Start rice.", "Sear sliced chicken, add veg, toss with soy, garlic, honey.", "Serve over rice."],
    popularity: 5,
    source: "library",
  },
  {
    id: "grilled-cheese-tomato-soup",
    title: "Grilled cheese and quick tomato soup",
    emoji: "🥪",
    minutes: 20,
    servings: 2,
    ingredients: [
      { foodId: "bread", key: true },
      { foodId: "cheddar", key: true },
      { foodId: "tomatoes", optional: true },
      { foodId: "heavy_cream", optional: true },
    ],
    staples: [S.tomatoes, S.butter, S.stock, S.salt],
    steps: ["Simmer canned tomatoes with stock 10 min, blend, finish with cream.", "Butter bread, griddle with cheddar until molten."],
    popularity: 4,
    source: "library",
  },
  {
    id: "salmon-spinach-pasta",
    title: "Creamy salmon and spinach pasta",
    emoji: "🍝",
    minutes: 25,
    servings: 3,
    ingredients: [
      { foodId: "salmon", key: true },
      { foodId: "spinach", key: true },
      { foodId: "heavy_cream", optional: true },
      { foodId: "lemons", optional: true },
      { foodId: "parmesan", optional: true },
    ],
    staples: [S.pasta, S.garlic, S.oil, S.salt],
    steps: ["Boil pasta.", "Flake seared salmon into a garlic-cream pan, wilt in spinach.", "Toss with pasta and lemon zest."],
    popularity: 11,
    source: "library",
  },
  {
    id: "bolognese",
    title: "Thirty-minute bolognese",
    emoji: "🍝",
    minutes: 30,
    servings: 4,
    ingredients: [
      { foodId: "ground_beef", key: true },
      { foodId: "onions" },
      { foodId: "carrots", optional: true },
      { foodId: "parmesan", optional: true },
    ],
    staples: [S.pasta, S.tomatoes, S.garlic, S.oil, S.salt],
    steps: ["Brown beef with onion and carrot.", "Add canned tomatoes, simmer 20 min.", "Toss with pasta, finish with parmesan."],
    popularity: 2,
    source: "library",
  },
  {
    id: "shakshuka",
    title: "Shakshuka with crusty bread",
    emoji: "🍅",
    minutes: 25,
    servings: 2,
    ingredients: [
      { foodId: "eggs", key: true },
      { foodId: "tomatoes", key: true },
      { foodId: "bell_pepper" },
      { foodId: "onions" },
      { foodId: "bread" },
      { foodId: "cilantro", optional: true },
    ],
    staples: [S.oil, S.garlic, S.spices, S.salt],
    steps: ["Soften onion and pepper, add tomatoes and spices, simmer.", "Crack eggs into wells, cover 5 min.", "Serve with torn bread."],
    popularity: 12,
    source: "library",
  },
  {
    id: "veggie-fried-rice",
    title: "Clean-out-the-fridge fried rice",
    emoji: "🍚",
    minutes: 15,
    servings: 3,
    ingredients: [
      { foodId: "eggs", key: true },
      { foodId: "carrots", optional: true },
      { foodId: "onions", optional: true },
      { foodId: "frozen_peas", optional: true },
      { foodId: "bell_pepper", optional: true },
      { foodId: "broccoli", optional: true },
    ],
    staples: [S.rice, S.soy, S.garlic, S.oil],
    steps: ["Fry veg hard in oil.", "Add rice, push aside, scramble eggs in.", "Soy, garlic, toss."],
    popularity: 8,
    source: "library",
  },
  {
    id: "chicken-caesar-wraps",
    title: "Chicken Caesar wraps",
    emoji: "🌯",
    minutes: 20,
    servings: 2,
    ingredients: [
      { foodId: "chicken_breast", key: true },
      { foodId: "lettuce", key: true },
      { foodId: "tortillas", key: true },
      { foodId: "parmesan", optional: true },
      { foodId: "lemons", optional: true },
    ],
    staples: [S.oil, S.garlic, S.salt],
    steps: ["Grill chicken, slice.", "Toss lettuce in lemon-garlic dressing.", "Roll in tortillas with parmesan."],
    popularity: 13,
    source: "library",
  },
  {
    id: "spinach-mushroom-quesadillas",
    title: "Spinach and mushroom quesadillas",
    emoji: "🫓",
    minutes: 15,
    servings: 2,
    ingredients: [
      { foodId: "tortillas", key: true },
      { foodId: "cheddar", key: true },
      { foodId: "spinach" },
      { foodId: "mushrooms", optional: true },
      { foodId: "salsa", optional: true },
    ],
    staples: [S.oil, S.salt],
    steps: ["Sauté mushrooms and spinach.", "Layer with cheddar in tortillas.", "Griddle until crisp, slice."],
    popularity: 15,
    source: "library",
  },
  {
    id: "sausage-peppers-sheetpan",
    title: "Sheet-pan sausage, peppers and potatoes",
    emoji: "🍖",
    minutes: 35,
    servings: 3,
    ingredients: [
      { foodId: "sausage", key: true },
      { foodId: "bell_pepper", key: true },
      { foodId: "onions" },
      { foodId: "potatoes" },
    ],
    staples: [S.oil, S.spices, S.salt],
    steps: ["Cube potatoes, roast 15 min.", "Add sausage, peppers, onion; roast 20 more."],
    popularity: 16,
    source: "library",
  },
  {
    id: "steak-potatoes-asparagus",
    title: "Steak with roasted potatoes and asparagus",
    emoji: "🥩",
    minutes: 35,
    servings: 2,
    ingredients: [
      { foodId: "steak", key: true },
      { foodId: "potatoes" },
      { foodId: "asparagus" },
    ],
    staples: [S.butter, S.garlic, S.salt, S.oil],
    steps: ["Roast potatoes.", "Sear steak, baste in garlic butter, rest.", "Blister asparagus in the steak pan."],
    popularity: 17,
    source: "library",
  },
  {
    id: "shrimp-avocado-tacos",
    title: "Shrimp tacos with avocado",
    emoji: "🌮",
    minutes: 20,
    servings: 2,
    ingredients: [
      { foodId: "shrimp", key: true },
      { foodId: "tortillas", key: true },
      { foodId: "avocados" },
      { foodId: "limes", optional: true },
      { foodId: "cabbage", optional: true },
      { foodId: "cilantro", optional: true },
    ],
    staples: [S.oil, S.spices, S.salt],
    steps: ["Toss shrimp in spices, sear 2 min a side.", "Mash avocado with lime.", "Assemble with slaw."],
    popularity: 18,
    source: "library",
  },
  {
    id: "tofu-broccoli-stirfry",
    title: "Crispy tofu and broccoli stir-fry",
    emoji: "🥦",
    minutes: 25,
    servings: 2,
    ingredients: [
      { foodId: "tofu", key: true },
      { foodId: "broccoli", key: true },
      { foodId: "ginger", optional: true },
      { foodId: "bell_pepper", optional: true },
    ],
    staples: [S.rice, S.soy, S.garlic, S.oil, S.honey],
    steps: ["Press and cube tofu, fry until golden.", "Stir-fry broccoli, add sauce and tofu.", "Serve over rice."],
    popularity: 19,
    source: "library",
  },
  {
    id: "banana-pancakes",
    title: "Banana pancakes (breakfast for dinner)",
    emoji: "🥞",
    minutes: 20,
    servings: 2,
    ingredients: [
      { foodId: "bananas", key: true },
      { foodId: "eggs", key: true },
      { foodId: "milk", key: true },
      { foodId: "strawberries", optional: true },
      { foodId: "yogurt", optional: true },
    ],
    staples: [S.flour, S.sugar, S.butter, S.honey],
    steps: ["Mash bananas into eggs, milk, flour.", "Griddle in butter.", "Top with strawberries and yogurt."],
    popularity: 20,
    source: "library",
  },
  {
    id: "caprese-bread",
    title: "Tomato, mozzarella and basil plate",
    emoji: "🍅",
    minutes: 10,
    servings: 2,
    ingredients: [
      { foodId: "tomatoes", key: true },
      { foodId: "mozzarella", key: true },
      { foodId: "basil" },
      { foodId: "bread" },
    ],
    staples: [S.oil, S.salt, S.vinegar],
    steps: ["Slice tomatoes and mozzarella, layer with basil.", "Oil, vinegar, salt. Toast bread alongside."],
    popularity: 21,
    source: "library",
  },
  {
    id: "chicken-rice-soup",
    title: "Chicken and rice soup",
    emoji: "🍲",
    minutes: 40,
    servings: 4,
    ingredients: [
      { foodId: "chicken_breast", key: true },
      { foodId: "carrots" },
      { foodId: "celery", optional: true },
      { foodId: "onions" },
    ],
    staples: [S.stock, S.rice, S.garlic, S.salt],
    steps: ["Sweat onion, carrot, celery.", "Add stock and chicken, simmer 20 min, shred.", "Add rice, cook until tender."],
    popularity: 22,
    source: "library",
  },
  {
    id: "pork-chops-zucchini",
    title: "Pan-seared pork chops with zucchini",
    emoji: "🍖",
    minutes: 25,
    servings: 2,
    ingredients: [
      { foodId: "pork_chops", key: true },
      { foodId: "zucchini" },
      { foodId: "potatoes", optional: true },
      { foodId: "lemons", optional: true },
    ],
    staples: [S.butter, S.garlic, S.salt, S.oil],
    steps: ["Sear chops 4 min a side, rest.", "Sauté zucchini in the pan with garlic and lemon."],
    popularity: 23,
    source: "library",
  },
  {
    id: "turkey-club",
    title: "Turkey club sandwiches",
    emoji: "🥪",
    minutes: 15,
    servings: 2,
    ingredients: [
      { foodId: "bread", key: true },
      { foodId: "deli_turkey", key: true },
      { foodId: "bacon", optional: true },
      { foodId: "lettuce" },
      { foodId: "tomatoes" },
      { foodId: "avocados", optional: true },
    ],
    staples: [S.salt],
    steps: ["Crisp bacon, toast bread.", "Stack turkey, bacon, lettuce, tomato."],
    popularity: 24,
    source: "library",
  },
  {
    id: "yogurt-berry-parfait-dinner",
    title: "Blueberry yogurt bowls with bananas",
    emoji: "🫐",
    minutes: 5,
    servings: 2,
    ingredients: [
      { foodId: "yogurt", key: true },
      { foodId: "blueberries", key: true },
      { foodId: "bananas", optional: true },
    ],
    staples: [S.honey, "oats"],
    steps: ["Layer yogurt, blueberries, banana and oats.", "Drizzle honey."],
    popularity: 25,
    source: "library",
  },
  {
    id: "mushroom-pasta",
    title: "Garlic mushroom pasta",
    emoji: "🍄",
    minutes: 20,
    servings: 2,
    ingredients: [
      { foodId: "mushrooms", key: true },
      { foodId: "spinach", optional: true },
      { foodId: "parmesan", optional: true },
      { foodId: "heavy_cream", optional: true },
    ],
    staples: [S.pasta, S.garlic, S.butter, S.oil, S.salt],
    steps: ["Brown mushrooms hard in butter.", "Add garlic, cream, wilt spinach.", "Toss with pasta and parmesan."],
    popularity: 26,
    source: "library",
  },
];
